---
- hosts: tag_Name_Packer_Builder
  become: yes

  tasks:
    - name: install git
      apt:
        name: git
        update_cache: yes
        state: latest

    - name: install tomcat8
      apt:
        name: tomcat8

    - name: install maven
      apt:
        name: maven
        state: latest
        
    - name: setup files
      git:
        repo: 'https://github.com/WiseHands/FootGo.git'
        version: 'release/1.0.0'
        dest: /home/ubuntu/footgo
    - name: setup db access
      script: script.sh

    - name: Set MAVEN_OPTS
      lineinfile:
        dest: /etc/environment
        state: present
        regexp: '^MAVEN_OPTS'
        line: 'MAVEN_OPTS=-Xmx1024m'

    - name: compile footgo app
      shell: mvn clean package
      args:
        chdir: /home/ubuntu/footgo
        #executable: /bin/bash
      environment:
        MAVEN_OPTS: -Xmx1024m
        MAVEN_HOME: /usr/share/maven
        JAVA_HOME: /usr/lib/jvm/java-1.11.0-openjdk-amd64

    - name: run site
      shell: cp /home/ubuntu/footgo/target/ROOT.war /var/lib/tomcat8/webapps/
